"""Lazy compatibility exports for historic ``synapse_memory.cli`` imports."""

from __future__ import annotations

import importlib
from typing import Any

_LAZY_ATTRS: dict[str, tuple[str, str]] = {
    "_arg_or_config": ("synapse_memory.cli.common", "_arg_or_config"),
    "_command_name": ("synapse_memory.cli.common", "_command_name"),
    "_daily_status_watcher": ("synapse_memory.cli.daily", "_daily_status_watcher"),
    "_enforce_cost_cap": ("synapse_memory.cli.common", "_enforce_cost_cap"),
    "_feedback_action": ("synapse_memory.cli.feedback", "_feedback_action"),
    "_feedback_targets": ("synapse_memory.cli.feedback", "_feedback_targets"),
    "_format_daily_status_line": (
        "synapse_memory.cli.daily",
        "_format_daily_status_line",
    ),
    "_hook_runtime_settings": ("synapse_memory.cli.setup", "_hook_runtime_settings"),
    "_interactive_guard": ("synapse_memory.cli.common", "_interactive_guard"),
    "_parse_stage_csv": ("synapse_memory.cli.daily", "_parse_stage_csv"),
    "_refresh_hook_sidecars": ("synapse_memory.cli.setup", "_refresh_hook_sidecars"),
    "_render_hook_settings_cache": (
        "synapse_memory.cli.setup",
        "_render_hook_settings_cache",
    ),
    "_resolve_model": ("synapse_memory.cli.common", "_resolve_model"),
    "_resolve_vault": ("synapse_memory.cli.common", "_resolve_vault"),
    "_runtime_ai_provider": ("synapse_memory.cli.common", "_runtime_ai_provider"),
    "_setup_profile_patterns_paths": (
        "synapse_memory.cli.setup",
        "_setup_profile_patterns_paths",
    ),
    "_setup_registry_path": ("synapse_memory.cli.setup", "_setup_registry_path"),
    "_stdout_is_tty": ("synapse_memory.cli.common", "_stdout_is_tty"),
    "AIError": ("synapse_memory.llm", "AIError"),
    "CompanyCard": ("synapse_memory.cards", "CompanyCard"),
    "CompactSourceResult": ("synapse_memory.wiki.compact", "CompactSourceResult"),
    "DEFAULT_CLAUDE_HOME": (
        "synapse_memory.collectors.claude_code",
        "DEFAULT_CLAUDE_HOME",
    ),
    "DEFAULT_CODEX_HOME": ("synapse_memory.collectors.codex", "DEFAULT_CODEX_HOME"),
    "DailyAlreadyRunningError": (
        "synapse_memory.status",
        "DailyAlreadyRunningError",
    ),
    "DiagnosticStatus": ("synapse_memory.doctor", "DiagnosticStatus"),
    "IngestResult": ("synapse_memory.wiki.ingest", "IngestResult"),
    "LaunchctlError": ("synapse_memory.wiki.launchd", "LaunchctlError"),
    "ProjectCard": ("synapse_memory.cards", "ProjectCard"),
    "STEPS": ("synapse_memory.daily", "STEPS"),
    "SUPPORTED_EXTENSIONS": ("synapse_memory.profile.ingest", "SUPPORTED_EXTENSIONS"),
    "StageStatus": ("synapse_memory.daily", "StageStatus"),
    "append_feedback_event": (
        "synapse_memory.feedback.events",
        "append_feedback_event",
    ),
    "apply_fix_actions": ("synapse_memory.doctor", "apply_fix_actions"),
    "apply_set_config_vault": ("synapse_memory.doctor", "apply_set_config_vault"),
    "ask": ("synapse_memory.endpoints.ask", "ask"),
    "ask_wiki": ("synapse_memory.wiki.query", "ask_wiki"),
    "audit_ingest_queue": (
        "synapse_memory.wiki.ingest_audit",
        "audit_ingest_queue",
    ),
    "build_feedback_event": ("synapse_memory.feedback.events", "build_feedback_event"),
    "cmd_ask": ("synapse_memory.cli.ask", "cmd_ask"),
    "cmd_assistant_status": ("synapse_memory.cli.config", "cmd_assistant_status"),
    "cmd_backfill": ("synapse_memory.cli.ingest", "cmd_backfill"),
    "cmd_card_list": ("synapse_memory.cli.cards", "cmd_card_list"),
    "cmd_card_new": ("synapse_memory.cli.cards", "cmd_card_new"),
    "cmd_card_show": ("synapse_memory.cli.cards", "cmd_card_show"),
    "cmd_cleanup_apply": ("synapse_memory.cli.cleanup", "cmd_cleanup_apply"),
    "cmd_cleanup_scan": ("synapse_memory.cli.cleanup", "cmd_cleanup_scan"),
    "cmd_collect_claude_code": (
        "synapse_memory.cli.ingest",
        "cmd_collect_claude_code",
    ),
    "cmd_collect_codex": ("synapse_memory.cli.ingest", "cmd_collect_codex"),
    "cmd_collect_obsidian": ("synapse_memory.cli.ingest", "cmd_collect_obsidian"),
    "cmd_compact_raw": ("synapse_memory.cli.ingest", "cmd_compact_raw"),
    "cmd_config_edit": ("synapse_memory.cli.config", "cmd_config_edit"),
    "cmd_config_get": ("synapse_memory.cli.config", "cmd_config_get"),
    "cmd_config_reset": ("synapse_memory.cli.config", "cmd_config_reset"),
    "cmd_config_set": ("synapse_memory.cli.config", "cmd_config_set"),
    "cmd_config_show": ("synapse_memory.cli.config", "cmd_config_show"),
    "cmd_config_validate": ("synapse_memory.cli.config", "cmd_config_validate"),
    "cmd_context": ("synapse_memory.cli.setup", "cmd_context"),
    "cmd_cost_summary": ("synapse_memory.cli.cost", "cmd_cost_summary"),
    "cmd_daily": ("synapse_memory.cli.daily", "cmd_daily"),
    "cmd_daily_status": ("synapse_memory.cli.daily", "cmd_daily_status"),
    "cmd_dismiss_list": ("synapse_memory.cli.profile", "cmd_dismiss_list"),
    "cmd_dismiss_profile": ("synapse_memory.cli.profile", "cmd_dismiss_profile"),
    "cmd_dismiss_purge_expired": (
        "synapse_memory.cli.profile",
        "cmd_dismiss_purge_expired",
    ),
    "cmd_doctor": ("synapse_memory.cli.doctor", "cmd_doctor"),
    "cmd_feedback": ("synapse_memory.cli.feedback", "cmd_feedback"),
    "cmd_hook": ("synapse_memory.cli.hook", "cmd_hook"),
    "cmd_ingest": ("synapse_memory.cli.ingest", "cmd_ingest"),
    "cmd_ingest_audit": ("synapse_memory.cli.ingest", "cmd_ingest_audit"),
    "cmd_ledger_show": ("synapse_memory.cli.profile", "cmd_ledger_show"),
    "cmd_lint": ("synapse_memory.cli.wiki", "cmd_lint"),
    "cmd_list_pending_profiles": (
        "synapse_memory.cli.profile",
        "cmd_list_pending_profiles",
    ),
    "cmd_me_decide": ("synapse_memory.cli.persona", "cmd_me_decide"),
    "cmd_me_draft_resume": ("synapse_memory.cli.persona", "cmd_me_draft_resume"),
    "cmd_me_generate": ("synapse_memory.cli.persona", "cmd_me_generate"),
    "cmd_me_recipes_list": ("synapse_memory.cli.persona", "cmd_me_recipes_list"),
    "cmd_me_recipes_show": ("synapse_memory.cli.persona", "cmd_me_recipes_show"),
    "cmd_me_update_profile": ("synapse_memory.cli.persona", "cmd_me_update_profile"),
    "cmd_me_what_did_i_think": (
        "synapse_memory.cli.persona",
        "cmd_me_what_did_i_think",
    ),
    "cmd_migrate_folders": ("synapse_memory.cli.cleanup", "cmd_migrate_folders"),
    "cmd_persona_design_project": (
        "synapse_memory.cli.persona",
        "cmd_persona_design_project",
    ),
    "cmd_persona_ingest": ("synapse_memory.cli.persona", "cmd_persona_ingest"),
    "cmd_profile_review_awaiting": (
        "synapse_memory.cli.profile",
        "cmd_profile_review_awaiting",
    ),
    "cmd_setup": ("synapse_memory.cli.setup", "cmd_setup"),
    "cmd_sync": ("synapse_memory.cli.setup", "cmd_sync"),
    "cmd_watch_install": ("synapse_memory.cli.watch", "cmd_watch_install"),
    "cmd_watch_run": ("synapse_memory.cli.watch", "cmd_watch_run"),
    "cmd_watch_status": ("synapse_memory.cli.watch", "cmd_watch_status"),
    "cmd_watch_uninstall": ("synapse_memory.cli.watch", "cmd_watch_uninstall"),
    "cmd_wiki_ask": ("synapse_memory.cli.wiki", "cmd_wiki_ask"),
    "collect_claude_code": (
        "synapse_memory.collectors.claude_code",
        "collect_claude_code",
    ),
    "collect_codex": ("synapse_memory.collectors.codex", "collect_codex"),
    "collect_obsidian": ("synapse_memory.collectors.obsidian", "collect_obsidian"),
    "compact_mirror_source": (
        "synapse_memory.wiki.compact",
        "compact_mirror_source",
    ),
    "companies_dir": ("synapse_memory.cards.company", "companies_dir"),
    "decide": ("synapse_memory.endpoints.persona", "decide"),
    "detect_ai_environment": ("synapse_memory.llm", "detect_ai_environment"),
    "diagnose_runtime_shim": ("synapse_memory.doctor", "diagnose_runtime_shim"),
    "diagnose_vault_config_consistency": (
        "synapse_memory.doctor",
        "diagnose_vault_config_consistency",
    ),
    "diagnose_wiki_maintenance": (
        "synapse_memory.doctor",
        "diagnose_wiki_maintenance",
    ),
    "diagnose_wiki_pages": ("synapse_memory.doctor", "diagnose_wiki_pages"),
    "draft_resume": ("synapse_memory.endpoints.persona", "draft_resume"),
    "extract_decision_patterns": (
        "synapse_memory.profile.extract",
        "extract_decision_patterns",
    ),
    "extract_profile_facts": (
        "synapse_memory.profile.extract",
        "extract_profile_facts",
    ),
    "get_vault_path": ("synapse_memory.config", "get_vault_path"),
    "ingest_files": ("synapse_memory.profile.ingest", "ingest_files"),
    "ingest_source": ("synapse_memory.wiki.ingest", "ingest_source"),
    "install_watch": ("synapse_memory.wiki.launchd", "install_watch"),
    "l0_root": ("synapse_memory.storage.l0", "l0_root"),
    "list_company_cards": ("synapse_memory.cards", "list_company_cards"),
    "list_project_cards": ("synapse_memory.cards", "list_project_cards"),
    "load_company_card": ("synapse_memory.cards", "load_company_card"),
    "load_last_answer": ("synapse_memory.feedback.last_response", "load_last_answer"),
    "load_project_card": ("synapse_memory.cards", "load_project_card"),
    "load_summary": ("synapse_memory.cost.summary", "load_summary"),
    "load_watermark": ("synapse_memory.wiki.watermark", "load_watermark"),
    "planned_fix_actions": ("synapse_memory.doctor", "planned_fix_actions"),
    "projects_dir": ("synapse_memory.cards.project", "projects_dir"),
    "render_summary_json": ("synapse_memory.cost.summary", "render_summary_json"),
    "render_summary_table": ("synapse_memory.cost.summary", "render_summary_table"),
    "resolve_card_target": ("synapse_memory.feedback.targets", "resolve_card_target"),
    "resolve_last_answer_targets": (
        "synapse_memory.feedback.targets",
        "resolve_last_answer_targets",
    ),
    "resolve_pattern_target": (
        "synapse_memory.feedback.targets",
        "resolve_pattern_target",
    ),
    "run_backfill": ("synapse_memory.wiki.backfill", "run_backfill"),
    "run_daily": ("synapse_memory.daily", "run_daily"),
    "run_doctor_fix": ("synapse_memory.cli.doctor", "run_doctor_fix"),
    "run_doctor_fix_config": (
        "synapse_memory.cli.doctor",
        "run_doctor_fix_config",
    ),
    "run_lint": ("synapse_memory.wiki.lint", "run_lint"),
    "run_watch_cycle": ("synapse_memory.wiki.daemon", "run_watch_cycle"),
    "run_with_ingest_lock": ("synapse_memory.wiki.lock", "run_with_ingest_lock"),
    "save_company_card": ("synapse_memory.cards", "save_company_card"),
    "save_profile_update": ("synapse_memory.profile.extract", "save_profile_update"),
    "save_project_card": ("synapse_memory.cards", "save_project_card"),
    "serialize_company_card": ("synapse_memory.cards", "serialize_company_card"),
    "serialize_project_card": ("synapse_memory.cards", "serialize_project_card"),
    "uninstall_watch": ("synapse_memory.wiki.launchd", "uninstall_watch"),
    "what_did_i_think": ("synapse_memory.endpoints.persona", "what_did_i_think"),
}



def get_lazy_attr(name: str) -> Any:
    try:
        module_name, attr_name = _LAZY_ATTRS[name]
    except KeyError as exc:
        raise AttributeError(name) from exc
    return getattr(importlib.import_module(module_name), attr_name)
